/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Map.java
 *
 * Created on 26 juin 2011, 20:25:37
 */
package test;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author wallouf
 */
public class Map extends javax.swing.JPanel {

    /**
     *  Creates new form Map
     * @param mapNumber indicate map to use 0->flat,1->down,2->left,3->right,4->left-down,5->right-down,6->full
     */
    public Map(int mapNumber) {
        this.mapNumber = mapNumber;
        initComponents();
        this.setVisible(true);
        Dimension n = new Dimension(20, 20);
        this.setSize(n);
        this.setMinimumSize(n);
        this.setMaximumSize(n);
    }

    public void openMap() {
        try {
            img0 = ImageIO.read(new File("./images/maps/ground_flat.jpg"));
            img1 = ImageIO.read(new File("./images/maps/ground_down.jpg"));
            img2 = ImageIO.read(new File("./images/maps/ground_left.gif"));
            img3 = ImageIO.read(new File("./images/maps/ground_right.jpg"));
            img4 = ImageIO.read(new File("./images/maps/ground_down_left.jpg"));
            img5 = ImageIO.read(new File("./images/maps/ground_down_right.jpg"));
            img6 = ImageIO.read(new File("./images/maps/ground.jpg"));
            //Pour une image de fond
        } catch (IOException e) {
            System.out.println("Error : " + e);
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        //Pour une image de fond
        switch (mapNumber) {
            case 0:
                g.setColor(cG);
                g.fillRect(0, 0, this.getWidth(), (int) (this.getHeight() * 0.2));
                g.setColor(cM);
                g.fillRect(0, (int) (this.getHeight() * 0.2), this.getWidth(), (int) (this.getHeight() * 0.8));
                break;
            case 1:
                g.setColor(cM);
                g.fillRect(0, 0, this.getWidth(), (int) (this.getHeight() * 0.8));
                g.setColor(cG);
                g.fillRect(0, (int) (this.getHeight() * 0.8), this.getWidth(), (int) (this.getHeight() * 0.2));
                break;
            case 2:
                setBackground(Color.DARK_GRAY);
                //ligne
                g.setColor(cG);
                int x0[] = {23, 3, -2, 18};
                int y0[] = {3, 23, 18, -2};
                g.fillPolygon(x0, y0, 4);
                //fill
                g.setColor(cM);
                int x1[] = {20, 20, 3};
                int y1[] = {3, 20, 20};
                g.fillPolygon(x1, y1, 3);
                break;
            case 3:
                setBackground(Color.DARK_GRAY);
                //ligne
                g.setColor(cG);
                int x2[] = {2, 22, 17, -3};
                int y2[] = {-2, 18, 23, 3};
                g.fillPolygon(x2, y2, 4);
                //fill
                g.setColor(cM);
                int x3[] = {0, 0, 17};
                int y3[] = {3, 20, 20};
                g.fillPolygon(x3, y3, 3);
                break;
            case 4:
                g.drawImage(img4, 0, 0, this.getWidth(), this.getHeight(), this);
                break;
            case 5:
                g.drawImage(img5, 0, 0, this.getWidth(), this.getHeight(), this);
                break;
            case 6:
                g.setColor(cM);
                g.fillRect(0, 0, this.getWidth(), this.getHeight());
                break;
            case 7:
                g.setColor(Color.DARK_GRAY);
                g.fillRect(0, 0, this.getWidth(), this.getHeight());
                break;
            case 10:
                g.setColor(Color.RED);
                g.fillRect(0, 0, this.getWidth(), this.getHeight());
                break;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    int mapNumber = 7;
    Image img0;
    Image img1;
    Image img2;
    Image img3;
    Image img4;
    Image img5;
    Image img6;
    Color cG = new Color(175, 163, 149);
    Color cM = new Color(62, 41, 36);
}
