/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main_menu.java
 *
 * Created on 26 juin 2011, 13:20:45
 */
package wormslike_menu;

import java.awt.Color;
import javax.swing.border.EtchedBorder;
import wormslike.WormsLike_Main;
import wormslike_IA.IA_Motor;
import wormslike_sound.Game_Sound;

/**
 *  menu concernant la video et le son
 * @author wallouf
 */
public class VideoSettings_Menu extends javax.swing.JPanel {
    //VARIABLES
    private int THEME = 0;
    private boolean mute = false;
    private static IA_Motor IA;

    //CONSTRUCTEUR PERMETTANT DE PASSER LA CLASSE PARENTE ET LE THEME EN COURS
    public VideoSettings_Menu(WormsLike_Main viewParent, int THEME) {
        this.THEME = THEME;
        this.viewParent = viewParent;
        initComponents();
        this.setBackground(Color.BLACK);
        buttonGroup1.add(jRadioButtonJungle);
        buttonGroup1.add(jRadioButtonMoon);
        buttonGroup1.add(jRadioButtonNormal);
        switch (THEME) {
            case 0:
                jRadioButtonNormal.setSelected(true);
                break;
            case 1:
                jRadioButtonMoon.setSelected(true);
                break;
            case 2:
                jRadioButtonJungle.setSelected(true);
                break;
        }
        mute = Game_Sound.isMute();
        jRadioButtonSoundMute.setSelected(mute);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelTheme = new javax.swing.JPanel();
        jRadioButtonNormal = new javax.swing.JRadioButton();
        jRadioButtonMoon = new javax.swing.JRadioButton();
        jRadioButtonJungle = new javax.swing.JRadioButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonApply = new javax.swing.JButton();
        jPanelSound = new javax.swing.JPanel();
        jRadioButtonSoundMute = new javax.swing.JRadioButton();
        jPanelMotor = new javax.swing.JPanel();
        jButtonMotor = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32000, 32000));
        setLayout(null);

        jPanelTheme.setBackground(new java.awt.Color(0, 0, 0));
        jPanelTheme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Theme Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N

        jRadioButtonNormal.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonNormal.setFont(new java.awt.Font("Arial", 0, 12));
        jRadioButtonNormal.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonNormal.setText("Normal");
        jRadioButtonNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNormalActionPerformed(evt);
            }
        });

        jRadioButtonMoon.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonMoon.setFont(new java.awt.Font("Arial", 0, 12));
        jRadioButtonMoon.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonMoon.setText("Moon");
        jRadioButtonMoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMoonActionPerformed(evt);
            }
        });

        jRadioButtonJungle.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonJungle.setFont(new java.awt.Font("Arial", 0, 12));
        jRadioButtonJungle.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonJungle.setText("Jungle");
        jRadioButtonJungle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJungleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelThemeLayout = new javax.swing.GroupLayout(jPanelTheme);
        jPanelTheme.setLayout(jPanelThemeLayout);
        jPanelThemeLayout.setHorizontalGroup(
            jPanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonNormal)
                    .addComponent(jRadioButtonMoon)
                    .addComponent(jRadioButtonJungle))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanelThemeLayout.setVerticalGroup(
            jPanelThemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonNormal)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMoon)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonJungle)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        add(jPanelTheme);
        jPanelTheme.setBounds(10, 10, 433, 270);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        add(jButtonCancel);
        jButtonCancel.setBounds(890, 590, 80, 23);

        jButtonApply.setText("Apply");
        jButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyActionPerformed(evt);
            }
        });
        add(jButtonApply);
        jButtonApply.setBounds(760, 590, 80, 23);

        jPanelSound.setBackground(new java.awt.Color(0, 0, 0));
        jPanelSound.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Audio Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N

        jRadioButtonSoundMute.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonSoundMute.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonSoundMute.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButtonSoundMute.setText("Mute ?");
        jRadioButtonSoundMute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSoundMuteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSoundLayout = new javax.swing.GroupLayout(jPanelSound);
        jPanelSound.setLayout(jPanelSoundLayout);
        jPanelSoundLayout.setHorizontalGroup(
            jPanelSoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonSoundMute)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanelSoundLayout.setVerticalGroup(
            jPanelSoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonSoundMute)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        add(jPanelSound);
        jPanelSound.setBounds(560, 10, 427, 270);

        jPanelMotor.setBackground(new java.awt.Color(0, 0, 0));
        jPanelMotor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Motor Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 51))); // NOI18N

        jButtonMotor.setText("Testing motor ?");
        jButtonMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMotorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMotorLayout = new javax.swing.GroupLayout(jPanelMotor);
        jPanelMotor.setLayout(jPanelMotorLayout);
        jPanelMotorLayout.setHorizontalGroup(
            jPanelMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMotor)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelMotorLayout.setVerticalGroup(
            jPanelMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMotorLayout.createSequentialGroup()
                .addComponent(jButtonMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanelMotor);
        jPanelMotor.setBounds(10, 300, 160, 80);
    }// </editor-fold>//GEN-END:initComponents
    //ON SAUVEGARDE LES CHOIX ET ON RETOURNE AU MENU
    private void jButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyActionPerformed
        WormsLike_Main.THEME = this.THEME;
        Game_Sound.setMute(mute);
        viewParent.changeView("retour_video");
    }//GEN-LAST:event_jButtonApplyActionPerformed
    //ON RETOURNE AU MENU SANS SAUVEGARDER
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        viewParent.changeView("retour_video");
    }//GEN-LAST:event_jButtonCancelActionPerformed
    //applique le theme normal
    private void jRadioButtonNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNormalActionPerformed
        this.THEME = 0;
    }//GEN-LAST:event_jRadioButtonNormalActionPerformed

    private void jRadioButtonSoundMuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSoundMuteActionPerformed
        mute = jRadioButtonSoundMute.isSelected();
    }//GEN-LAST:event_jRadioButtonSoundMuteActionPerformed
    //applique le theme lune
    private void jRadioButtonMoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMoonActionPerformed
        this.THEME = 1;
}//GEN-LAST:event_jRadioButtonMoonActionPerformed
    //applique le theme jungle
    private void jRadioButtonJungleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJungleActionPerformed
        this.THEME = 2;
}//GEN-LAST:event_jRadioButtonJungleActionPerformed

    private void jButtonMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMotorActionPerformed
        if(IA==null){
            IA = new IA_Motor();
            IA.setVisible(true);
        } else if(IA!=null && !IA.isVisible()){
            IA.setVisible(true);
        }
    }//GEN-LAST:event_jButtonMotorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonApply;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonMotor;
    private javax.swing.JPanel jPanelMotor;
    private javax.swing.JPanel jPanelSound;
    private javax.swing.JPanel jPanelTheme;
    private javax.swing.JRadioButton jRadioButtonJungle;
    private javax.swing.JRadioButton jRadioButtonMoon;
    private javax.swing.JRadioButton jRadioButtonNormal;
    private javax.swing.JRadioButton jRadioButtonSoundMute;
    // End of variables declaration//GEN-END:variables
    EtchedBorder eB = new EtchedBorder(Color.GRAY, Color.BLACK);
    EtchedBorder eBD = new EtchedBorder(Color.BLACK, Color.BLACK);
    WormsLike_Main viewParent;
}
